config/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings
from monitoring.views import index_view

urlpatterns = [
    path('admin/', admin.site.urls),

] + i18n_patterns(
    path('i18n/', include('django.conf.urls.i18n')),
    path('', index_view, name="home"),
    path('test/', include('monitoring.urls')),
    path('user/', include('user.urls')),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

monitoring/urls.py
from django.urls import path

from monitoring.views import subjects_view, variants_view, subject_list_view, result_view, result_list_view, \
    VariantCreateView

app_name = "monitoring"
urlpatterns = [
    path('subjects/', subject_list_view, name="subject_list"),
    path('subjects/<int:pk>/', subjects_view, name="subjects"),
    path('variants/<int:pk>/', variants_view, name="variants"),
    path('results/', result_list_view, name="result_list"),
    path('results/<int:pk>/', result_view, name="result"),

    # Teachers
    path('variants/create/', VariantCreateView.as_view(), name="variant_create"),
]

user/urls.py
from django.urls import path, include

from user import views
from user.views import RegisterView, loguot_view, ProfileView, DeleteProfileView, EditProdileView

app_name = "user"
urlpatterns = [
    path('register/', RegisterView.as_view(), name="register"),
    path('login/', views.sign_in, name='login'),
    path('logout/', loguot_view, name="logout"),
    path('profile/<int:pk>/', ProfileView.as_view(), name="profile"),
    path('edit_profile/<int:pk>/', EditProdileView.as_view(), name="edit_profile"),
    path('delete_profile/<int:pk>/', DeleteProfileView.as_view(), name="delete_profile"),
]

templates/pages/delete_profile.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
	Delete profile
{% endblock %}

{% block content %}
    <form method="post">
        <p>{{ object }}{% blocktrans %} - are you sure?{% endblocktrans %}</p>
        {% csrf_token %}
        {{ form }}
        <button type="submit">{% blocktrans %}Delete{% endblocktrans %}</button>
    </form>
{% endblock %}

templates/pages/edit_profile.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
    Edit profile
{% endblock %}

{% block content %}
    <div class="container">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">{% blocktrans %}Save{% endblocktrans %}</button>
        </form>
    </div>
{% endblock %}

templates/pages/exercise_page.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block title %}
    Variant: {{ variant.title }}
{% endblock %}

{% block content %}
    <div class="container">
        <h2>{{ variant.title }}</h2>
        <form method="post">
            {% csrf_token %}
            <ol>
                {% for exercise in exercise_list %}
                    <li>
                        <h6>{{ exercise.text }}</h6>
                        <p>
                            <input type="radio" name="{{ exercise.id }}" id="{{ exercise.id }}_answer_a"
                                   value="answer_a">
                            <label for="{{ exercise.id }}_answer_a">{{ exercise.answer_a }}</label>
                        </p>
                        <p>
                            <input type="radio" name="{{ exercise.id }}" id="{{ exercise.id }}_answer_b"
                                   value="answer_b">
                            <label for="{{ exercise.id }}_answer_b">{{ exercise.answer_b }}</label>
                        </p>
                        <p>
                            <input type="radio" name="{{ exercise.id }}" id="{{ exercise.id }}_answer_c"
                                   value="answer_c">
                            <label for="{{ exercise.id }}_answer_c">{{ exercise.answer_c }}</label>
                        </p
                        >
                        <p>
                            <input type="radio" name="{{ exercise.id }}" id="{{ exercise.id }}_answer_d"
                                   value="answer_d">
                            <label for="{{ exercise.id }}_answer_d">{{ exercise.answer_d }}</label>
                        </p>
                    </li>
                {% endfor %}
            </ol>
            {% if request.user.is_authenticated == True %}
                <button type="submit">{% blocktrans %}Tekshirish{% endblocktrans %}</button>
            {% endif %}
            {% if request.user.is_authenticated == False %}
                <a href="{% url "user:register" %}">{% blocktrans %}Register to take the test{% endblocktrans %}</a>
            {% endif %}
        </form>

    </div>
{% endblock %}

templates/pages/home_page.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block title %}
    Home
{% endblock %}

{% block content %}
    <div class="container">
        <h1>{% blocktrans %}Hi{% endblocktrans %}</h1>
    </div>
{% endblock %}

templates/pages/login_page.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Login
{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block content %}
    <form method="POST" class="reg_log_form log_form">
        {% csrf_token %}
        <h2>Sign in</h2>
        {{ form.as_div }}
        <button type="submit" class="btn btn-success">Sign in</button>
    </form>
    <div style="display: flex; gap: 10px; justify-content: center; margin-top: 10px">
        <p>Don't have an account? Go to register --></p>
        <a href="{% url "user:register" %}">Sign up</a>
    </div>
{% endblock %}

{% block extra_js %}
    <script src="{% static 'js/script.js' %}"></script>
{% endblock %}

templates/pages/profile.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
    Profile page
{% endblock %}

{% block content %}
    <div class="container" style="margin-top: 50px;">
        <div class="avatar-wrap">
            <img src="{{ user.avatar.url }}" alt=""
                 style="object-fit: cover; object-position: center; width: 250px; height: 250px; border-radius: 10px">
        </div>
        <div style="display: flex; width: 250px; justify-content: space-between; margin-top: 25px;">
            <a class="btn btn-outline-warning" href="{% url "user:edit_profile" object.pk %}">{% blocktrans %}
                Edit{% endblocktrans %}</a>
            <a class="btn btn-outline-danger" href="{% url "user:delete_profile" object.pk %}">{% blocktrans %}
                Delete{% endblocktrans %}</a>
        </div>
        <div style="display: flex; flex-direction: column; align-items: center; width: 250px; margin-top: 50px;">
            <h5>{{ user.username }}</h5>
            <h5>{{ user.first_name }}</h5>
            <h5>{{ user.last_name }}</h5>
            <h5>{{ user.email }}</h5>
            <a class="btn btn-outline-primary" href="{% url "monitoring:result_list" %}"
               style=" width: 250px; margin-top: 25px;">{% blocktrans %}Rezultatlar{% endblocktrans %}</a>
        </div>
    </div>
{% endblock %}

templates/pages/register_page.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Sign up page
{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block content %}
    <div>
        <form action="{% url "user:register" %}" method="post" class="reg_log_form reg_form">
            {% csrf_token %}
            <h2>Sign up</h2>
            {{ form.as_div }}
            <button type="submit" class="btn btn-success">Sign up</button>
        </form>
        <div style="display: flex; gap: 10px; justify-content: center; margin-top: 10px">
            <p>Do you have an account? Go to login --></p>
            <a href="{% url "user:login" %}">Sign in</a>
        </div>
    </div>
{% endblock %}

templates/pages/result_list_page.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block title %}
	Results
{% endblock %}

{% block content %}
    <div class="container" style="margin-top: 25px">

        {% if result_list %}
            <div class="list-group" data-bs-theme="dark">
                {% for result in result_list %}
                    <a href="{% url "monitoring:result" result.id %}" class="list-group-item list-group-item-action"
                       aria-current="true">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1">{{ result }}</h5>
                            <small>{{ result.date_completed|date:"d/m/Y H:s:i" }}</small>
                        </div>
                    </a>
                {% endfor %}
            </div>
        {% endif %}

    </div>
{% endblock %}

templates/pages/result_page.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block title %}
    Result
{% endblock %}

{% block content %}
    <div class="container">
        <h3>{% blocktrans %}Natijangiz{% endblocktrans %}: {{ ball }} / {{ count }}</h3>

        <ol>
            {% for result in object_list %}
                <li>
                    <h6>{{ result.exercise.text }}</h6>

                    <p>
                        A) {{ result.exercise.answer_a }}
                        <span style="color: {% if result.user_answer == 'answer_a' %}
                            {% if result.exercise.answer == 'answer_a' %} green {% else %} red {% endif %}
                        {% endif %}">
                            {% if result.user_answer == 'answer_a' %}
                                {% if result.exercise.answer == 'answer_a' %}✓{% else %}✕{% endif %}
                            {% endif %}
                        </span>
                    </p>

                    <p>
                        B) {{ result.exercise.answer_b }}
                        <span style="color: {% if result.user_answer == 'answer_b' %}
                            {% if result.exercise.answer == 'answer_b' %} green {% else %} red {% endif %}
                        {% endif %}">
                            {% if result.user_answer == 'answer_b' %}
                                {% if result.exercise.answer == 'answer_b' %}✓{% else %}✕{% endif %}
                            {% endif %}
                        </span>
                    </p>

                    <p>
                        C) {{ result.exercise.answer_c }}
                        <span style="color: {% if result.user_answer == 'answer_c' %}
                            {% if result.exercise.answer == 'answer_c' %} green {% else %} red {% endif %}
                        {% endif %}">
                            {% if result.user_answer == 'answer_c' %}
                                {% if result.exercise.answer == 'answer_c' %}✓{% else %}✕{% endif %}
                            {% endif %}
                        </span>
                    </p>

                    <p>
                        D) {{ result.exercise.answer_d }}
                        <span style="color: {% if result.user_answer == 'answer_d' %}
                            {% if result.exercise.answer == 'answer_d' %} green {% else %} red {% endif %}
                        {% endif %}">
                            {% if result.user_answer == 'answer_d' %}
                                {% if result.exercise.answer == 'answer_d' %}✓{% else %}✕{% endif %}
                            {% endif %}
                        </span>
                    </p>

                </li>
            {% endfor %}
        </ol>

        <a href="{% url 'monitoring:result_list' %}">Страница результатов</a>
    </div>
{% endblock %}

templates/pages/subjects_page.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block title %}
    Fanlar
{% endblock %}

{% block content %}
    <div class="container">
        <h1>{% blocktrans %}FANLAR{% endblocktrans %}</h1>
        {% for subject in subject_list %}
            <ul style="list-style: none">
                <li>
                    <a href="{% url 'monitoring:subjects' subject.id %}">{{ subject.name }}</a>
                </li>
            </ul>
        {% endfor %}
    </div>
{% endblock %}

templates/pages/variant_create.html
{% extends 'base.html' %}
{% load widget_tweaks %}


{% block title %}
    Variant create
{% endblock %}

{% block content %}
    <div class="container py-5">
        <h1>Variant yaratish:</h1>
        <form method="post">
            {% csrf_token %}
            {% for field in variant_form %}
                <div class="fieldWrapper mt-3">
                    {{ field|add_label_class:"form-label" }}
                    {{ field|add_class:"form-control" }}
                </div>
            {% endfor %}

            <hr>

            <div class="row">
                {% for form in formset %}
                    <div class="col-4 shadow p-3 mb-5 bg-body-tertiary rounded">
                        {% for field in form %}
                            {% if field.name not in "id, variant" %}
                                {{ field|add_label_class:"form-label mt-3" }}
                                {{ field|add_class:"form-control"|attr:"rows:3" }}
                            {% endif %}
                        {% endfor %}
                    </div>
                {% endfor %}
            </div>

            <button type="submit" class="btn btn-outline-success mt-4">Saqlash</button>
        </form>
    </div>
{% endblock %}

templates/pages/variant_page.html
{% extends 'base.html' %}
{% load i18n %}


{% block title %}
    VARIANTLAR
{% endblock %}

{% block content %}
    <div class="container">
        <h1>{% blocktrans %}VARIANTLAR{% endblocktrans %}</h1>
        <div class="list-group">
            {% for variant in variant_list %}
                {% if request.user.is_staff %}
                    {% if request.user.is_staff == 1 %}
                        <div class="list-group-item list-group-item-action" style="display: flex; justify-content: space-between;">
                            <a href="{% url 'monitoring:variants' variant.id %}">{{ variant.title }}</a>
                            <div style="display: flex; align-items: center;">
                                <a href="{% url 'monitoring:variant_create' %}?subject={{ subject.id|urlencode }}">Qo'shish</a>
                            </div>
                        </div>
                    {% endif %}
                    {#                        <a href="{% url 'monitoring:variant_edit' variant.id %}" class="ms-auto">O'zgartirish</a>#}
                    {#                        <a href="{% url 'monitoring:variant_delete' variant.id %}" class="ms-4">O'chirish</a>#}

                {% else %}
                    <div class="list-group-item list-group-item-action">
                        <a class="btn" href="{% url 'monitoring:variants' variant.id %}">{{ variant.title }}</a>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock %}