config/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings
from monitoring.views import index_view

urlpatterns = [
    path('admin/', admin.site.urls),

] + i18n_patterns(
    path('i18n/', include('django.conf.urls.i18n')),
    path('', index_view, name="home"),
    path('test/', include('monitoring.urls')),
    path('user/', include('user.urls')),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

monitoring/urls.py
from django.urls import path

from monitoring.views import subjects_view, variants_view, subject_list_view, result_view, result_list_view, \
    VariantCreateView

app_name = "monitoring"
urlpatterns = [
    path('subjects/', subject_list_view, name="subject_list"),
    path('subjects/<int:pk>/', subjects_view, name="subjects"),
    path('variants/<int:pk>/', variants_view, name="variants"),
    path('results/', result_list_view, name="result_list"),
    path('results/<int:pk>/', result_view, name="result"),

    # Teachers
    path('variants/create/', VariantCreateView.as_view(), name="variant_create"),
]

user/urls.py
from django.urls import path, include

from user import views
from user.views import RegisterView, loguot_view, ProfileView, DeleteProfileView, EditProdileView

app_name = "user"
urlpatterns = [
    path('register/', RegisterView.as_view(), name="register"),
    path('login/', views.sign_in, name='login'),
    path('logout/', loguot_view, name="logout"),
    path('profile/<int:pk>/', ProfileView.as_view(), name="profile"),
    path('edit_profile/<int:pk>/', EditProdileView.as_view(), name="edit_profile"),
    path('delete_profile/<int:pk>/', DeleteProfileView.as_view(), name="delete_profile"),
]

templates/components/navbar.html
{% load i18n %}
<nav class="navbar navbar-expand-lg bg-body-secondary">
    <div class="container">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% url "home" as home %}
                    <a class="nav-link {% if request.path == home %} active {% endif %} " aria-current="page"
                       href="{{ home }}">{% blocktrans %}Home{% endblocktrans %}</a>
                </li>
                <li class="nav-item">
                    {% url "monitoring:subject_list" as subject %}
                    <a class="nav-link {% if request.path == subject %} active {% endif %} " href="{{ subject }}">
                        {% blocktrans %}Subjects{% endblocktrans %}</a>
                </li>
            </ul>

            <div class="form-check form-switch mx-2">
                <input class="form-check-input p-2" type="checkbox" role="switch" id="flexSwitchCheckChecked" checked
                       onclick="myFunction()">
            </div>

            <form action="{% url 'set_language' %}" method="post">
                {% csrf_token %}
                <input name="next" type="hidden" value="{{ redirect_to }}">
                <select class="form-select" name="language" onchange="this.form.submit()">
                    {% get_current_language as LANGUAGE_CODE %}
                    {% get_available_languages as LANGUAGES %}
                    {% get_language_info_list for LANGUAGES as languages %}
                    {% for language in languages %}
                        <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %}
                                selected{% endif %}>
                            {{ language.name_local | slice:3 | upper }}
                        </option>
                    {% endfor %}
                </select>
            </form>

            <div class="d-flex gap-2 d-md-flex justify-content-md-end ms-2">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item dropdown">
                        <a class="nav-link" href="#" role="button" data-bs-toggle="dropdown">
                            {% if request.user.is_authenticated %}
                                <img src="{{ user.avatar.url }}" alt=""
                                     style="width: 25px; height: 25px; border-radius: 50%; object-fit: cover; object-position: center;">
                            {% else %}
                                <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor"
                                     class="bi bi-person-circle" viewBox="0 0 16 16">
                                    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/>
                                    <path fill-rule="evenodd"
                                          d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1"/>
                                </svg>
                            {% endif %}
                        </a>
                        <ul class="dropdown-menu">
                            {% if request.user.is_authenticated %}
                                <li><a class="dropdown-item" href="{% url "user:profile" request.user.pk %}">
                                    {% blocktrans %}Profile{% endblocktrans %}</a>
                                </li>
                                <hr class="dropdown-divider">
                                <li><a class="dropdown-item" href="{% url "user:logout" %}">{% blocktrans %}Log
                                    out{% endblocktrans %}</a></li>
                            {% else %}
                                <li><a class="dropdown-item" href="{% url "user:login" %}">{% blocktrans %}Sign
                                    in{% endblocktrans %}</a></li>
                                <li><a class="dropdown-item" href="{% url "user:register" %}">{% blocktrans %}Sign
                                    up{% endblocktrans %}</a></li>
                            {% endif %}
                        </ul>
                    </li>
                </ul>
            </div>

        </div>
    </div>
</nav>